language: python
cache: pip
python:
  - "3.4"
install:
  - pip install -U pip wheel
  - pip install -r requirements.txt
script: py.test
notifications:
  email:
    recipients:
      - code@iatistandard.org
    on_success: change
    on_failure: always
